version: '3.8'

services:
  grafana:
    image: grafana/grafana
    container_name: grafana-provisioning
    restart: unless-stopped
    environment:
      - GF_INSTALL_PLUGINS=yesoreyeram-infinity-datasource
      - GF_AUTH_ANONYMOUS_ENABLED=true
    volumes:
      - 'grafana_storage:/var/lib/grafana'
    ports:
      - "3000:3000"
volumes:
  grafana_storage: {}
